---
  - name: PLAY 1 - PRINTING OUT IOS HOSTNAME AND NETWORK OS
    hosts: "iosxe"
    connection: network_cli
    gather_facts: no
    tasks:

    - name: "TASK 1 - SEND A SINGLE ENABLE LEVEL SHOW COMMAND"
      cisco.ios.ios_command:
        commands: "show version"

    - name: "TASK 2 - SEND MULTIPLE ENABLE LEVEL SHOW COMMAND"
      cisco.ios.ios_command:
        commands:
        - "show ip interface brief"
        - "show interfaces"
        - "dir"
