---
  - name: PLAY 1 - SENDING SHOW COMMANDS TO IOS DEVICES
    hosts: "iosxe"
    connection: network_cli
    gather_facts: no
    tasks:

      - name: run multiple commands on remote nodes
        cisco.ios.ios_command:
            commands:
              - "show version"
              - "show interfaces"
        register: show_command_output

      - name: Show Commands to Disk
        ansible.builtin.template:
          src: "show_command.j2"
          dest: "show_outputs/{{ inventory_hostname }}_show_cmds.txt"
