
---
  - name: PLAY 1 - FACTS
    hosts: "iosxe"
    connection: network_cli
    gather_facts: no
    tasks:

      - name: Gather listed vlans with provided configurations
        cisco.ios.ios_vlans:
          config:
          state: gathered