
---
  - name: PLAY 1 - FACTS
    hosts: "iosxe"
    connection: network_cli
    gather_facts: no
    tasks:

      - name: Merge provided configuration with device configuration
        cisco.ios.ios_interfaces:
          config:
          - name: Loopback140
            description: Configured and Merged by Ansible Network
            enabled: true
          - name: Loopback145
            description: Configured and Merged by Ansible Network
            mtu: 2800
            enabled: false
            speed: 100
            duplex: full
          state: merged