---
  - name: PLAY 1 - FACTS
    hosts: "iosxe"
    connection: network_cli
    gather_facts: no
    tasks:

        - name: render a Jinja2 template onto an IOS device
          ios_config:
            backup: yes
            src: "../templates/simple-acl.j2"
