---
  - name: PLAY 1 - FACTS
    hosts: "iosxe"
    connection: network_cli
    gather_facts: no
    tasks:
      - name: run multiple commands on remote nodes
        cisco.ios.ios_command:
            commands:
              - "show version"
              - "show ip interface brief"
              - "show interfaces"
        register: show_command_output

      - name: Show Commands to Disk
        ansible.builtin.template:
          src: "../templates/show_command.j2"
          dest: "show_outputs/pre_checks_{{ inventory_hostname }}_show_cmds.txt"

      - name: Second Task - Configure Interface 
        ios_config:
          lines:
              - "description configured by Ansible"
              - "ip address 155.0.0.0 255.255.255.0"
          parents: interface Loopback1450


      - name: run multiple commands on remote nodes
        cisco.ios.ios_command:
            commands:
              - "show version"
              - "show ip interface brief"
              - "show interfaces"
        register: show_command_output

      - name: Show Commands to Disk
        ansible.builtin.template:
          src: "../templates/show_command.j2"
          dest: "show_outputs/post_checks_{{ inventory_hostname }}_show_cmds.txt"