
---
  - name: PLAY 1 - FACTS
    hosts: "iosxe"
    connection: network_cli
    gather_facts: no
    tasks:
        - name: First Task - Configure CDP and LLDP 
          ios_config:
            lines:
                - no cdp run
                - no lldp run

        - name: "Purge given interfaces (Note: This will delete the interface itself)"
          cisco.ios.ios_interfaces:
            config:
            - name: Loopback1337
            - name: Loopback124
            - name: Loopback125
            state: purged